import "../globals.css";
import Footer from "@/partials/Footer";
import Header from "@/partials/Header";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Helo Job",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="max-w-7xl mx-auto">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
